services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: saadoon
      POSTGRES_PASSWORD: s@@doon123
      POSTGRES_DB: fastAPI
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_db:
